// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpwdlbmcruyakdpvqrdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwd2RsYm1jcnV5YWtkcHZxcmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDYwNTYsImV4cCI6MjA2MjcyMjA1Nn0.B-zGVswtg7Ivra_Zy40EwLXockpT9_OJNdMcgbGGJWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);